{
 "title": "dmarc dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "% compliant",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dmarc_compliant_total)/sum(dmarc_total)"
    }
   ]
  },
  {
   "title": "% rejected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dmarc_reject_total)/sum(dmarc_total)"
    }
   ]
  },
  {
   "title": "% quarantine",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dmarc_quarantine_total)/sum(dmarc_total)"
    }
   ]
  },
  {
   "title": "# by reporter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dmarc_compliant_total) by (reporter)",
     "legendFormat": "Comliant by {{reporter}}"
    },
    {
     "expr": "sum(dmarc_reject_total) by (reporter)",
     "legendFormat": "Reyect by {{reporter}}"
    }
   ]
  },
  {
   "title": "# by sender domain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dmarc_compliant_total) by (dkim_domain)",
     "legendFormat": "Compliant {{dkim_domain}}"
    },
    {
     "expr": "sum(dmarc_reject_total) by (dkim_domain)",
     "legendFormat": "Rejected by {{dkim_domain}}"
    }
   ]
  }
 ]
}