name: Get latest release
description: Gets the latest (non-prerelease) version of a PyPI package.
inputs:
  package:
    description: Name of the the package.
    required: true
outputs:
  latest_version:
    description: Latest version of the package.
    value: ${{ steps.get-latest.outputs.VERSION }}
runs:
  using: composite
  steps:
    - name: Create venv
      run: python3 -m venv venv
      shell: bash

    - name: Install packaging
      run: venv/bin/pip install packaging requests
      shell: bash

    - name: Get latest version
      id: get-latest
      run: venv/bin/python3 ./.github/actions/get-latest-release/get_latest_release.py ${{ inputs.package }} >> "$GITHUB_OUTPUT"
      shell: bash
